{ ... }:
{
  flake.modules.hostenv.redis =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      cfg = config.services.redis;

      quote = value: "\"${builtins.replaceStrings [ "\\" "\"" ] [ "\\\\" "\\\"" ] value}\"";

      generatedConfigFile = pkgs.writeText "valkey.conf" ''
        ${cfg.extraConfig}

        # Hostenv runs Valkey as a per-environment user service and exposes it
        # only through a Unix socket. These directives are deliberately applied
        # after extraConfig so project config cannot accidentally open a TCP/TLS
        # or RDMA listener, or enable the cluster bus.
        port 0
        tls-port 0
        rdma-port 0
        cluster-enabled no
        unixsocket ${quote cfg.socket}
        unixsocketperm 0700

        dir ${quote cfg.dataDir}
        appendonly ${if cfg.appendOnly then "yes" else "no"}

        daemonize no
        supervised systemd
        logfile ""
      '';
    in
    {
      options.services.redis = {
        enable = lib.mkEnableOption "a Redis-compatible Valkey server";

        package = lib.mkOption {
          type = lib.types.package;
          default = pkgs.valkey;
          defaultText = "pkgs.valkey";
          description = "Valkey package providing a systemd-supervision-enabled `valkey-server`.";
        };

        dataDir = lib.mkOption {
          type = lib.types.singleLineStr;
          default = config.hostenv.dataDir + "/redis";
          defaultText = lib.literalExpression ''config.hostenv.dataDir + "/redis"'';
          description = "Persistent data directory used by Valkey.";
        };

        socket = lib.mkOption {
          type = lib.types.str;
          readOnly = true;
          default = "${config.hostenv.runtimeDir}/redis.sock";
          defaultText = lib.literalExpression ''config.hostenv.runtimeDir + "/redis.sock"'';
          description = "Unix socket used to connect to the Redis-compatible server.";
        };

        appendOnly = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Whether to enable Valkey append-only persistence.";
        };

        extraConfig = lib.mkOption {
          type = lib.types.lines;
          default = "";
          description = ''
            Additional non-secret Valkey configuration. This content is copied
            to the Nix store. Hostenv's socket-only networking and runtime
            directives are applied afterward.
          '';
        };

        configFile = lib.mkOption {
          type = lib.types.path;
          readOnly = true;
          default = generatedConfigFile;
          defaultText = "A Valkey configuration file automatically generated by Nix.";
          description = "Generated Valkey configuration file.";
        };
      };

      config = lib.mkIf cfg.enable {
        assertions = [
          {
            assertion = lib.hasPrefix "/" cfg.dataDir;
            message = "services.redis.dataDir must be an absolute path";
          }
        ];

        systemd.services.redis = {
          description = "Valkey Redis-compatible server";
          wantedBy = [ "default.target" ];
          restartTriggers = [ cfg.configFile ];

          preStart = ''
            mkdir -p ${lib.escapeShellArg cfg.dataDir}
            chmod 0700 ${lib.escapeShellArg cfg.dataDir}
            rm -f ${lib.escapeShellArg cfg.socket}
          '';

          script = ''
            exec ${cfg.package}/bin/valkey-server ${cfg.configFile}
          '';

          # Valkey's systemd supervision sends READY=1 only after startup is
          # complete. Type=notify therefore keeps dependent units ordered
          # After=redis.service from starting while Valkey is still loading.
          postStart = ''
            redis_sock=${lib.escapeShellArg cfg.socket}
            if [ ! -S "$redis_sock" ]; then
              echo "hostenv: Valkey reported ready without creating $redis_sock" >&2
              exit 1
            fi
          '';

          # Do not leave a stale socket that could make deploy-time readiness
          # checks think a stopped/crashed service is still available.
          postStop = ''
            rm -f ${lib.escapeShellArg cfg.socket}
          '';

          serviceConfig = {
            Type = "notify";
            Restart = "on-failure";
            RestartSec = "5s";
            # Large persisted datasets can legitimately take longer than
            # systemd's default start/stop timeout to load or shut down.
            TimeoutStartSec = "infinity";
            TimeoutStopSec = "infinity";
            UMask = "0077";
          };
        };

        profile = [ cfg.package ];
      };
    };
}
