{ inputs, lib, config, ... }:
let
  cfgTop = config;
  fp = inputs.flake-parts.lib;
  providerEnabled = cfgTop.provider.enable or false;
  hostenvInputs = cfgTop.flake.lib.hostenvInputs;
  addressableContentInput =
    hostenvInputs.requireInput {
      inherit inputs;
      name = "addressable-content";
      context = "hostenv dev shell";
    };
in
{
  options.perSystem = fp.mkPerSystemOption ({ config, pkgs, ... }:
    let
      providerServiceHaskellDeps = cfgTop.flake.lib.provider.service.haskellDeps or [ ];
      hostenvDeployAgentHaskellDeps = cfgTop.flake.lib.provider.deployAgent.haskellDeps or [ ];
      ghcPackageNames = lib.unique (config.hostenv.haskell.devPackages ++ providerServiceHaskellDeps ++ hostenvDeployAgentHaskellDeps ++ [ "addressable-content" ]);
      providerHaskellPackages = pkgs.haskell.packages.ghc912.override {
        overrides = self: super: {
          addressable-content = self.callCabal2nix "addressable-content" addressableContentInput.outPath { };
        };
      };
      devGhc = providerHaskellPackages.ghcWithPackages (p: map (name: p.${name}) ghcPackageNames);
      cabalHook = ''
        if command -v ghc >/dev/null; then
          libdir="$(ghc --print-libdir)"
          pkgdb="''${libdir}/package.conf.d"
          cat > "$PWD/cabal.project.local" <<EOF
        -- Generated by nix develop (flake-parts/devshells.nix)
        packages:
          ./modules/services/hostenv-provider-service
          ./modules/services/hostenv-deploy-agent
          ./provider
        package-dbs: clear, ''${pkgdb}
        with-compiler: ghc
        EOF
        fi
      '';
    in
    {
      options.hostenv.haskell.devPackages = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        description = "Haskell package names contributed by micro-projects for the default dev shell GHC environment.";
      };

      config = lib.mkIf (!(inputs ? hostenv)) {
        hostenv.haskell.devPackages =
          [ "haskell-language-server" ]
          ++ (lib.attrByPath [ "provider" "haskellDevPackages" ] [ ] config);
        devshells.default = {
          devshell =
            let
              providerDemo = pkgs.writeShellApplication {
                name = "provider-demo";
                runtimeInputs = [ pkgs.gum pkgs.postgresql ];
                text = ''
                  set -euo pipefail

                  # Switch to the project root directory.
                  ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
                  pushd "$ROOT"
                  # Run the demo script
                  exec ${pkgs.bash}/bin/bash ./examples/local-provider-migration/run-demo.sh "$@"
                  popd
                '';
              };
              # For Postgres
              pgConfig = pkgs.writeShellScriptBin "pg_config" ''
                exec ${pkgs.libpq.pg_config} "$@"
              '';
            in
            {
              packages =
                (lib.optional providerEnabled config.packages.hostenv-provider)
                ++ [
                  pkgs.jq
                  pkgs.sops
                  pkgs.age
                  pkgs.haskellPackages.cabal-install
                  devGhc
                  pkgs.gum
                  pkgs.pkg-config
                  pkgs.postgresql
                  pgConfig
                  providerDemo
                ];
              startup.cabal-project = { text = cabalHook; };
            };
          env = [
            {
              name = "DEVSHELL_NO_MOTD";
              value = 1;
            }
            # Fix Haskell library compilation issues, especially anything
            # built on postgres libraries.
            {
              name = "PKG_CONFIG_PATH";
              value = "${pkgs.libpq.dev}/lib/pkgconfig:${pkgs.openssl.dev}/lib/pkgconfig";
            }
            {
              name = "LD_LIBRARY_PATH";
              value = lib.makeLibraryPath [ pkgs.libpq pkgs.openssl ];
            }
          ];
        };
      };
    });
}
