{ pkgs, makeHostenv, documentationEnabled }:

# Fast/unit-style suites
(import ./restic.nix { inherit pkgs; })
  // (import ./deploy-rsync.nix { inherit pkgs makeHostenv; })
  // (import ./hostenv-assertions.nix { inherit pkgs makeHostenv; })
  // (import ./cli-wrappers.nix { inherit pkgs makeHostenv; })
  // (import ./cli-command-names.nix { inherit pkgs makeHostenv; })
  // (import ./cli-flags.nix { inherit pkgs makeHostenv; })
  // (import ./cli-spinner.nix { inherit pkgs; })
  // (import ./hostenv-provider-service.nix { inherit pkgs documentationEnabled; })
  // (import ./provider-cli.nix { inherit pkgs documentationEnabled; })
  // (import ./backups-repo-host.nix { inherit pkgs makeHostenv; })
  // (import ./mysql-backups.nix { inherit pkgs; })
  // (import ./redis.nix { inherit pkgs; })
  // (import ./mysql-backups-dependency.nix { inherit pkgs makeHostenv; })
  // (import ./migrate-tags.nix { inherit pkgs makeHostenv; })
  // (import ./php-app-migrate.nix { inherit pkgs makeHostenv; })
  // (import ./required-secret-files.nix { inherit pkgs makeHostenv; })
  // (import ./packages.nix { inherit pkgs makeHostenv; })
